version: "3"
services:
  shop_service:
    image: shop_service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - .:/shop_service # host folder:container folder
    command: 'npm run start:dev'
    environment:
      env_file:
        -.env
  shop_db:
    image: postgres:13
    restart: "always"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - shop_db

# add volume
