version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - "5672:5672" #is the main RabbitMQ port that our NestJS application will use
      - "15672:15672" # is the port of the management plugin. It provides an interface that lets us manage and monitor our RabbitMQ instance
    env_file:
      - ./rabbitmq.env
  api_gateway:
    image: api_gateway
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001" # Local_port:container_port
    volumes:
      - .:/api_gateway
    command: 'npm run start:dev'
    environment:
      env_file:
        -.env
        - raabbitmq.env
