version: "3"
services:
  user_service:
    image: user_service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3003" # Local_port:container_port
    volumes:
      - .:/user_service
    command: 'npm run start:dev'
    environment:
      env_file:
        -.env
  user_db:
    image: postgres:13
    restart: "always"
    ports:
      - "5434:5434"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - "8080:8080"
#    depends_on:
#      - user_db

# volume add
